#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx
  - curl
  - jq

write_files:
  - path: /usr/local/bin/setup-dashboard.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/bin/bash
      set -eux

      WEBROOT=/var/www/html

      systemctl enable nginx
      systemctl start nginx

      # Remove default nginx page
      rm -f ${WEBROOT}/index.nginx-debian.html

      # Download dashboard files
      curl -L https://raw.githubusercontent.com/Ashutoshdocs/lectureAzure/main/VMSS/index.html -o ${WEBROOT}/index.html
      curl -L https://raw.githubusercontent.com/Ashutoshdocs/lectureAzure/main/VMSS/style.css -o ${WEBROOT}/style.css
      curl -L https://raw.githubusercontent.com/Ashutoshdocs/lectureAzure/main/VMSS/script.js -o ${WEBROOT}/script.js

      # Azure Metadata
      META=$(curl -H Metadata:true -s \
      "http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01")

      HOSTNAME=$(echo "$META" | jq -r '.name')
      REGION=$(echo "$META" | jq -r '.location')

      cat > ${WEBROOT}/config.js <<EOF
      window.AZURE_CONFIG = {
          hostname: "$HOSTNAME",
          region: "$REGION",
          bootEpoch: $(date +%s)
      };
      EOF

      chown -R www-data:www-data ${WEBROOT}
      chmod -R 755 ${WEBROOT}

      systemctl restart nginx

runcmd:
  - bash /usr/local/bin/setup-dashboard.sh

final_message: |
  ==========================================
  Azure VMSS Dashboard Installed
  ==========================================
